[general]
live_config_reload= true

[window]
opacity = 0.6
blur= false
startup_mode= "Windowed"
title= "Alacritty"
dynamic_title= true
class= {instance= "Alacritty", general= "Alacritty"}
decorations_theme_variant= "None"
level= "AlwaysOnTop"

[colors]
primary= {foreground= "#d5d5d5", background= "#151515"}

[scrolling]
history= 10000
multiplier= 3

[font]
normal= {family= "JetBrainsMono Nerd Font", style= "Regular"}
bold= {family= "JetBrainsMono Nerd Font", style= "Bold"}
italic= {family= "JetBrainsMono Nerd Font", style= "Italic"}
bold_italic= {family= "JetBrainsMono Nerd Font", style= "Bold Italic"}
size= 11.25
offset= {x= 0, y= 0}

[cursor]
style= {shape= "Beam", blinking= "On"}
unfocused_hollow= false
blink_interval= 750
blink_timeout= 0
thickness= 0.15

[mouse]
hide_when_typing= true

[keyboard]
bindings= [{key= "Return", mods= "Super|Shift", action= "SpawnNewInstance"}]
