# Minimal keymap.toml - only customizations, merges with defaults
# See: https://github.com/sxyazi/yazi/tree/shipped/yazi-config/preset

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    # Custom: Open Alacritty terminal in current directory
	{ on = "T", run = "shell -- setsid alacritty --working-directory .", desc = "Open terminal in current directory" },
    # Custom: Open Neovim in current directory, closes Yazi
    { on = "n", run = "shell '~/.local/bin/yazi-to-neovim \"$PWD\"'",  desc = "Open Neovim in current directory, closes Yazi" },
    # Custom: Open Neovim in new Alacritty without closing Yazi
    { on = "N", run = "shell -- setsid alacritty --working-directory . -e nvim .",  desc = "Open Neovim in current directory without closing Yazi" },
]
